version: '3'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        hostname: zookeeper
        container _ name: zookeeper
        ports:
            - "2181:2181"
    environment:
        ZOOKEEPER-CLIENT-PORT: 2181
        ZOOKEEPER-TICK_TIME: 2000
    healthcheck:
        test: [ 'CMD', 'bash', '-c', "echo 'ruok' | nc localhost 2181" ]
        interval: 1OS
        timeout: 5s
        retries: 5s
    networks: -confluent


    broker :configs:
    